const jCategory = [
  {
    index: 0,
    image: "../images/google.png",
    title: "Web Developer",
    rate: "30k-60k/m",
    av: "Full-Time",
    companyName: "Google",
    location: "USA",
    vacancy: "10",
    hours: "50h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from home",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 5 year(s)",
  },
  {
    index: 1,
    image: "../images/uber.png",
    title: "Business Associate",
    rate: "30k-60k/m",
    av: "Freelancer",
    companyName: "Uber",
    location: "india",
    vacancy: "50",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 1 year(s)",
  },
  {
    index: 2,
    image: "../images/linkedin.png",
    title: "Business Associate",
    rate: "30k-60k/m",
    av: "Full Time",
    companyName: "linkedin",
    location: "india",
    vacancy: "200",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "1 to 5 year(s)",
  },
  {
    index: 3,
    image: "../images/facebook.png",
    title: "Digital Marketing",
    rate: "30k-60k/m",
    av: "Full Time",
    companyName: "Facebook",
    location: "USA",
    vacancy: "50",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 5 year(s)",
  },
  {
    index: 4,
    image: "../images/yahoo.png",
    title: "User Experience ",
    rate: "30k-60k/m",
    av: "Full Time",
    companyName: "yahoo",
    location: "Pune",
    vacancy: "50",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 1 year(s)",
  },
  {
    index: 5,
    image: "../images/apple.png",
    title: "Web Developer ",
    rate: "30k-60k/m",
    av: "Full Time",
    companyName: "Apple",
    location: "USA",
    vacancy: "50",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 2 year(s)",
  },

  {
    index: 6,
    image: "../images/instagram.png",
    title: "Product Designer",
    rate: "30k-60k/m",
    av: "Part Time",
    companyName: "Instagram",
    location: "Noida",
    vacancy: "50",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 1 year(s)",
  },

  {
    index: 7,
    image: "../images/wordpress.png",
    title: "Software Developer",
    rate: "30k-60k/m",
    av: "Full Time",
    companyName: "Wordpress",
    location: "Pune",
    vacancy: "500",
    hours: "40h/week",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)",
    workplace: "Work from office",
    education: "Bachelor degree in any computer Science Course",
    experience: "0 to 5 year(s)",
  },
];
